name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: npm install
        
      - name: Run tests
        run: npm test
      
      # - name: Send coverage report to Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
        
      # - name: Send coverage report to Codecov
      #   uses: Atrox/codecov-action@v0.1.2
      #   env: 
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
      
      # - name: Send coverage report to Code Climate
      #   uses: paambaati/codeclimate-action@v2.7.5
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }} 
